name: widget_carousel_flutter
description: "Widget Carousel Flutter"
version: 1.0.0
homepage: https://github.com/andersonmatte/widget_carousel_flutter
repository: https://github.com/andersonmatte/widget_carousel_flutter
issue_tracker: https://github.com/andersonmatte/widget_carousel_flutter/issues
documentation: https://github.com/andersonmatte/widget_carousel_flutter#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/