name: flutter_carousel
description: "Flutter Carousel"
version: 1.0.0
homepage: https://github.com/andersonmatte/flutter_carousel
repository: https://github.com/andersonmatte/flutter_carousel
issue_tracker: https://github.com/andersonmatte/flutter_carousel/issues
documentation: https://github.com/andersonmatte/flutter_carousel#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/